export const FORD_MODELS = [
  'F-150', 'F-150 Raptor', 'F-250', 'F-350', 'F-450',
  'Expedition', 'Expedition Max', 'Explorer', 'Explorer ST',
  'Mustang', 'Mustang GT', 'Shelby GT500',
  'Bronco', 'Bronco Sport', 'Ranger', 'Ranger Raptor',
  'Edge', 'Edge ST', 'Escape', 'Taurus', 'Crown Victoria',
  'Flex', 'Fusion', 'EcoSport', 'Transit'
]

export const SERVICE_TYPES = ['maintenance', 'repair', 'programming']

export const WORK_ORDER_STATUS = [
  'received', 'diagnosis', 'in_progress', 'done', 'delivered'
]

export const STATUS_COLORS = {
  received: 'bg-blue-500',
  diagnosis: 'bg-yellow-500',
  in_progress: 'bg-orange-500',
  done: 'bg-green-500',
  delivered: 'bg-gray-500',
}

export const USER_ROLES = { ADMIN: 'admin', TECHNICIAN: 'technician' }

export const WHATSAPP_NUMBER = '96550540999'

export const CURRENCY = 'KWD'

export const WORK_ORDER_TEMPLATES = [
  {
    id: 'periodic',
    services: ['oil_change', 'filter_change', 'inspection'],
  },
  {
    id: 'computer',
    services: ['ecu_diagnostic', 'code_reading'],
  },
  {
    id: 'brakes',
    services: ['brake_pads', 'brake_discs', 'brake_fluid'],
  },
]

export const YEARS = Array.from({ length: 35 }, (_, i) => 2025 - i)

// Ford Common DTC Codes Database
export const DTC_DATABASE = [
  // Engine - Powertrain
  { code: 'P0100', description: 'Mass Air Flow (MAF) Circuit Malfunction', category: 'Engine' },
  { code: 'P0101', description: 'MAF Sensor Range/Performance', category: 'Engine' },
  { code: 'P0102', description: 'MAF Sensor Circuit Low Input', category: 'Engine' },
  { code: 'P0103', description: 'MAF Sensor Circuit High Input', category: 'Engine' },
  { code: 'P0106', description: 'MAP/BARO Pressure Circuit Range/Performance', category: 'Engine' },
  { code: 'P0107', description: 'MAP Sensor Circuit Low Input', category: 'Engine' },
  { code: 'P0108', description: 'MAP Sensor Circuit High Input', category: 'Engine' },
  { code: 'P0110', description: 'Intake Air Temperature Sensor Circuit', category: 'Engine' },
  { code: 'P0112', description: 'IAT Sensor Circuit Low Input', category: 'Engine' },
  { code: 'P0113', description: 'IAT Sensor Circuit High Input', category: 'Engine' },
  { code: 'P0116', description: 'Engine Coolant Temp Circuit Range/Performance', category: 'Engine' },
  { code: 'P0117', description: 'ECT Sensor Circuit Low Input', category: 'Engine' },
  { code: 'P0118', description: 'ECT Sensor Circuit High Input', category: 'Engine' },
  { code: 'P0120', description: 'Throttle Position Sensor Circuit Malfunction', category: 'Engine' },
  { code: 'P0121', description: 'TPS Range/Performance', category: 'Engine' },
  { code: 'P0122', description: 'TPS Circuit Low Input', category: 'Engine' },
  { code: 'P0123', description: 'TPS Circuit High Input', category: 'Engine' },
  { code: 'P0125', description: 'Insufficient Coolant Temp for Closed Loop', category: 'Engine' },
  { code: 'P0128', description: 'Coolant Thermostat Below Regulating Temp', category: 'Engine' },
  { code: 'P0130', description: 'O2 Sensor Circuit Malfunction (Bank 1 Sensor 1)', category: 'Engine' },
  { code: 'P0131', description: 'O2 Sensor Low Voltage (Bank 1 Sensor 1)', category: 'Engine' },
  { code: 'P0132', description: 'O2 Sensor High Voltage (Bank 1 Sensor 1)', category: 'Engine' },
  { code: 'P0133', description: 'O2 Sensor Slow Response (Bank 1 Sensor 1)', category: 'Engine' },
  { code: 'P0135', description: 'O2 Sensor Heater Circuit (Bank 1 Sensor 1)', category: 'Engine' },
  { code: 'P0136', description: 'O2 Sensor Circuit (Bank 1 Sensor 2)', category: 'Engine' },
  { code: 'P0150', description: 'O2 Sensor Circuit (Bank 2 Sensor 1)', category: 'Engine' },
  { code: 'P0151', description: 'O2 Sensor Low Voltage (Bank 2 Sensor 1)', category: 'Engine' },
  { code: 'P0152', description: 'O2 Sensor High Voltage (Bank 2 Sensor 1)', category: 'Engine' },
  { code: 'P0171', description: 'System Too Lean (Bank 1)', category: 'Fuel' },
  { code: 'P0172', description: 'System Too Rich (Bank 1)', category: 'Fuel' },
  { code: 'P0174', description: 'System Too Lean (Bank 2)', category: 'Fuel' },
  { code: 'P0175', description: 'System Too Rich (Bank 2)', category: 'Fuel' },
  { code: 'P0190', description: 'Fuel Rail Pressure Sensor Circuit', category: 'Fuel' },
  { code: 'P0191', description: 'Fuel Rail Pressure Sensor Range/Performance', category: 'Fuel' },
  { code: 'P0193', description: 'Fuel Rail Pressure Sensor High Input', category: 'Fuel' },
  { code: 'P0200', description: 'Injector Circuit Malfunction', category: 'Fuel' },
  { code: 'P0201', description: 'Injector Circuit - Cylinder 1', category: 'Fuel' },
  { code: 'P0202', description: 'Injector Circuit - Cylinder 2', category: 'Fuel' },
  { code: 'P0203', description: 'Injector Circuit - Cylinder 3', category: 'Fuel' },
  { code: 'P0204', description: 'Injector Circuit - Cylinder 4', category: 'Fuel' },
  { code: 'P0205', description: 'Injector Circuit - Cylinder 5', category: 'Fuel' },
  { code: 'P0206', description: 'Injector Circuit - Cylinder 6', category: 'Fuel' },
  { code: 'P0207', description: 'Injector Circuit - Cylinder 7', category: 'Fuel' },
  { code: 'P0208', description: 'Injector Circuit - Cylinder 8', category: 'Fuel' },
  { code: 'P0217', description: 'Engine Overheating Condition', category: 'Engine' },
  { code: 'P0219', description: 'Engine Overspeed Condition', category: 'Engine' },
  { code: 'P0230', description: 'Fuel Pump Primary Circuit', category: 'Fuel' },
  { code: 'P0300', description: 'Random/Multiple Cylinder Misfire Detected', category: 'Ignition' },
  { code: 'P0301', description: 'Cylinder 1 Misfire Detected', category: 'Ignition' },
  { code: 'P0302', description: 'Cylinder 2 Misfire Detected', category: 'Ignition' },
  { code: 'P0303', description: 'Cylinder 3 Misfire Detected', category: 'Ignition' },
  { code: 'P0304', description: 'Cylinder 4 Misfire Detected', category: 'Ignition' },
  { code: 'P0305', description: 'Cylinder 5 Misfire Detected', category: 'Ignition' },
  { code: 'P0306', description: 'Cylinder 6 Misfire Detected', category: 'Ignition' },
  { code: 'P0307', description: 'Cylinder 7 Misfire Detected', category: 'Ignition' },
  { code: 'P0308', description: 'Cylinder 8 Misfire Detected', category: 'Ignition' },
  { code: 'P0316', description: 'Engine Misfire on Startup (First 1000 Rev)', category: 'Ignition' },
  { code: 'P0320', description: 'Ignition/Distributor Engine Speed Input Circuit', category: 'Ignition' },
  { code: 'P0325', description: 'Knock Sensor 1 Circuit (Bank 1)', category: 'Ignition' },
  { code: 'P0335', description: 'Crankshaft Position Sensor A Circuit', category: 'Engine' },
  { code: 'P0336', description: 'CKP Sensor A Range/Performance', category: 'Engine' },
  { code: 'P0340', description: 'Camshaft Position Sensor Circuit (Bank 1)', category: 'Engine' },
  { code: 'P0341', description: 'CMP Sensor Range/Performance (Bank 1)', category: 'Engine' },
  { code: 'P0345', description: 'Camshaft Position Sensor Circuit (Bank 2)', category: 'Engine' },
  { code: 'P0351', description: 'Ignition Coil A Primary/Secondary Circuit', category: 'Ignition' },
  { code: 'P0352', description: 'Ignition Coil B Primary/Secondary Circuit', category: 'Ignition' },
  { code: 'P0353', description: 'Ignition Coil C Primary/Secondary Circuit', category: 'Ignition' },
  { code: 'P0354', description: 'Ignition Coil D Primary/Secondary Circuit', category: 'Ignition' },
  { code: 'P0400', description: 'EGR Flow Malfunction', category: 'Emission' },
  { code: 'P0401', description: 'EGR Insufficient Flow Detected', category: 'Emission' },
  { code: 'P0402', description: 'EGR Excessive Flow Detected', category: 'Emission' },
  { code: 'P0411', description: 'Secondary Air Injection System Incorrect Flow', category: 'Emission' },
  { code: 'P0420', description: 'Catalyst System Efficiency Below Threshold (Bank 1)', category: 'Emission' },
  { code: 'P0430', description: 'Catalyst System Efficiency Below Threshold (Bank 2)', category: 'Emission' },
  { code: 'P0440', description: 'EVAP Emission Control System Malfunction', category: 'Emission' },
  { code: 'P0441', description: 'EVAP System Incorrect Purge Flow', category: 'Emission' },
  { code: 'P0442', description: 'EVAP System Leak Detected (Small Leak)', category: 'Emission' },
  { code: 'P0443', description: 'EVAP Purge Control Valve Circuit', category: 'Emission' },
  { code: 'P0446', description: 'EVAP Vent Control Circuit', category: 'Emission' },
  { code: 'P0455', description: 'EVAP System Leak Detected (Large Leak)', category: 'Emission' },
  { code: 'P0456', description: 'EVAP System Leak Detected (Very Small Leak)', category: 'Emission' },
  { code: 'P0460', description: 'Fuel Level Sensor Circuit', category: 'Fuel' },
  { code: 'P0500', description: 'Vehicle Speed Sensor Malfunction', category: 'Transmission' },
  { code: 'P0505', description: 'Idle Air Control System', category: 'Engine' },
  { code: 'P0506', description: 'Idle Air Control System RPM Lower Than Expected', category: 'Engine' },
  { code: 'P0507', description: 'Idle Air Control System RPM Higher Than Expected', category: 'Engine' },
  // Transmission
  { code: 'P0700', description: 'Transmission Control System Malfunction', category: 'Transmission' },
  { code: 'P0705', description: 'Transmission Range Sensor Circuit (PRNDL)', category: 'Transmission' },
  { code: 'P0710', description: 'Transmission Fluid Temperature Sensor Circuit', category: 'Transmission' },
  { code: 'P0715', description: 'Input/Turbine Speed Sensor Circuit', category: 'Transmission' },
  { code: 'P0720', description: 'Output Speed Sensor Circuit', category: 'Transmission' },
  { code: 'P0730', description: 'Incorrect Gear Ratio', category: 'Transmission' },
  { code: 'P0731', description: 'Gear 1 Incorrect Ratio', category: 'Transmission' },
  { code: 'P0732', description: 'Gear 2 Incorrect Ratio', category: 'Transmission' },
  { code: 'P0733', description: 'Gear 3 Incorrect Ratio', category: 'Transmission' },
  { code: 'P0734', description: 'Gear 4 Incorrect Ratio', category: 'Transmission' },
  { code: 'P0735', description: 'Gear 5 Incorrect Ratio', category: 'Transmission' },
  { code: 'P0741', description: 'Torque Converter Clutch Stuck Off', category: 'Transmission' },
  { code: 'P0750', description: 'Shift Solenoid A Malfunction', category: 'Transmission' },
  { code: 'P0755', description: 'Shift Solenoid B Malfunction', category: 'Transmission' },
  { code: 'P0760', description: 'Shift Solenoid C Malfunction', category: 'Transmission' },
  // Body & Electrical
  { code: 'B1200', description: 'Climate Control Push Button Circuit Failure', category: 'Body' },
  { code: 'B1213', description: 'Anti-Theft Number of Programmed Keys is Below Minimum', category: 'Body' },
  { code: 'B1232', description: 'Antenna Not Connected', category: 'Body' },
  { code: 'B1317', description: 'Battery Voltage High', category: 'Electrical' },
  { code: 'B1318', description: 'Battery Voltage Low', category: 'Electrical' },
  { code: 'B1342', description: 'ECU is Faulted', category: 'Electrical' },
  { code: 'B1359', description: 'Ignition Run/Accessory Circuit Failure', category: 'Electrical' },
  { code: 'B1600', description: 'PATS Received Incorrect Key Code', category: 'Body' },
  { code: 'B1601', description: 'PATS Received Invalid Key Code', category: 'Body' },
  { code: 'B1602', description: 'PATS Received Invalid Format of Key Code', category: 'Body' },
  { code: 'B1681', description: 'PATS Transceiver Signal Not Received', category: 'Body' },
  { code: 'B2103', description: 'Antenna Not Connected', category: 'Body' },
  // Chassis - ABS
  { code: 'C0031', description: 'Left Front Wheel Speed Sensor Circuit', category: 'ABS' },
  { code: 'C0032', description: 'Right Front Wheel Speed Sensor Circuit', category: 'ABS' },
  { code: 'C0033', description: 'Left Rear Wheel Speed Sensor Circuit', category: 'ABS' },
  { code: 'C0034', description: 'Right Rear Wheel Speed Sensor Circuit', category: 'ABS' },
  { code: 'C0035', description: 'Left Front Wheel Speed Sensor', category: 'ABS' },
  { code: 'C0040', description: 'Right Front Wheel Speed Sensor', category: 'ABS' },
  { code: 'C0045', description: 'Left Rear Wheel Speed Sensor', category: 'ABS' },
  { code: 'C0050', description: 'Right Rear Wheel Speed Sensor', category: 'ABS' },
  { code: 'C0265', description: 'EBCM Motor Relay Circuit', category: 'ABS' },
  // Communication
  { code: 'U0001', description: 'High Speed CAN Communication Bus', category: 'Communication' },
  { code: 'U0073', description: 'Control Module Communication Bus Off', category: 'Communication' },
  { code: 'U0100', description: 'Lost Communication with ECM/PCM', category: 'Communication' },
  { code: 'U0101', description: 'Lost Communication with TCM', category: 'Communication' },
  { code: 'U0121', description: 'Lost Communication with ABS', category: 'Communication' },
  { code: 'U0131', description: 'Lost Communication with Power Steering Module', category: 'Communication' },
  { code: 'U0140', description: 'Lost Communication with Body Control Module', category: 'Communication' },
  { code: 'U0155', description: 'Lost Communication with Instrument Cluster', category: 'Communication' },
  { code: 'U0164', description: 'Lost Communication with HVAC Module', category: 'Communication' },
  { code: 'U0401', description: 'Invalid Data Received from ECM/PCM', category: 'Communication' },
  { code: 'U0415', description: 'Invalid Data Received from ABS Module', category: 'Communication' },
  { code: 'U1900', description: 'CAN Communication Bus Fault', category: 'Communication' },
]
